version = 1
SPDX-PackageName = "Agora"
SPDX-PackageSupplier = "Nextcloud contributors"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/agora"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2023 Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**.map"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2023 Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["**.json", "**.toml", "**.xml", "**.php", "**.md", "**.sql"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2023 Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["img/**", "svg/**", "css/fonts/**", "assets/dist/img/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2023 Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["l10n/**", "l10nextra/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2023 Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
